### ISSUE TITLE
LMS not deploying

### ISSUE THREAD

**Issue by sfraser131** [logicwar/logitechmediaserver#1]
Running TrueNAS SCALE 22.12.2. I have 3 TRUEHARTS apps installed, QB, PLEX and Logitech Media Server (LMS). 1st two are runnign fine, LMS is stuck in deployment. I currently have disabled Host Path Safety checks, but ran into the same LMS deployment issue prior to any SMB SHARES being created, or turned on for that matter. I have also tried to create the LMS app with out any external storage or host path configuration specified. I have also tried manually specifying the apps user/grp id . Each case i get the same result, LMS stuck in deploying (over 12 hours). The LMS APP log file is empty. I apologise if my terminology is off , or I have left out important information. I am happy to respond to questions. Hardware is listed below. Any suggestions are appreciated.

**Comment by logicwar** [comment]
Unfortunately, I can't help regarding your specific hardware and OS.  I am running this docker image without a problem on QNAP Container Station and on a standard PC with Ubuntu. You could run in an infinite loop at boot if you don’t create and specify a specific user/grp as explained when using a persistent folder. But if you tried to create the container without any external storage it should work like a charm. I just recreated 5 instances without any problem.
